# Generated by Django 4.0.3 on 2022-04-11 14:57

import django.contrib.postgres.fields
from django.db import migrations, models
import question.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'text'), ('one_answer', 'one_answer'), ('many_answers', 'many_answers'), ('comparison', 'comparison')], default='text', max_length=60)),
                ('question', models.CharField(default=None, max_length=500)),
                ('text_answer', models.CharField(default=None, max_length=100, null=True)),
                ('answer_options', models.JSONField(default=question.models.default_answer_option, null=True)),
                ('right_answers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None)),
            ],
        ),
    ]
